name: CustomJoinMessage
version: '${project.version}-b${build.timestamp}'
main: dev.nixend.customjoinmessage.CustomJoinMessagePlugin
api-version: '1.21'
author: Nixend
description: Кастомные сообщения при входе/выходе игроков с поддержкой плейсхолдеров и анимаций
website: https://github.com/Nixend-creator/CustomJoinMessage
softdepend: [PlaceholderAPI]
commands:
  cjm:
    description: Управление плагином CustomJoinMessage
    usage: /<command> reload
    permission: customjoinmessage.reload
permissions:
  customjoinmessage.reload:
    description: Перезагрузка конфигурации
    default: op