name: CustomJoinMessage
version: '${project.version}-b${build.timestamp}'
main: dev.nixend.customjoinmessage.CustomJoinMessagePlugin
api-version: '1.21'
author: Nixend
description: Custom join/quit messages with animations and admin notifications
website: https://github.com/Nixend-creator/CustomJoinMessage
softdepend: [PlaceholderAPI]
commands:
  cjm:
    description: Manage CustomJoinMessage plugin
    usage: /<command> reload
    permission: customjoinmessage.reload
permissions:
  customjoinmessage.reload:
    description: Reload plugin configuration
    default: op